name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install unzip and wget
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Trivy Filesystem Scan
      run: trivy fs --format table -o new.txt .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t charansait372/devtask:latest .

    - name: Trivy Image Scan
      run: trivy image --format table -o new2.txt charansait372/devtask:latest

    - name: DockerHub login
      uses: docker-login/action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker push charansait372/devtask:latest

    - name: Kubectl Apply
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f deployment-service.yaml 
